//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TitchyCottage.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductQuantity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductQuantity()
        {
            this.ShopTransactions = new HashSet<ShopTransaction>();
            this.ShopTransactionHistories = new HashSet<ShopTransactionHistory>();
            this.ProductTransactionHistories = new HashSet<ProductTransactionHistory>();
        }
    
        public long ID { get; set; }
        public int ProductID { get; set; }
        public string Lot { get; set; }
        public string DateCode { get; set; }
        public Nullable<decimal> TotalQuantity { get; set; }
        public System.DateTime ExpiredDate { get; set; }
        public Nullable<decimal> StockInQuantity { get; set; }
        public Nullable<decimal> ShopInQuantity { get; set; }
        public Nullable<decimal> SoldOutQuantity { get; set; }
        public Nullable<System.DateTime> ManufacturerDate { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopTransaction> ShopTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopTransactionHistory> ShopTransactionHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductTransactionHistory> ProductTransactionHistories { get; set; }
    }
}
