//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TitchyCottage.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopTransaction
    {
        public long ID { get; set; }
        public string ShopID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<long> ProductQuantityID { get; set; }
        public decimal TotalQuantity { get; set; }
        public decimal StockInQuantity { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> SoldOutQuantity { get; set; }
    
        public virtual ProductQuantity ProductQuantity { get; set; }
    }
}
